language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing"

before_script:
  - echo "no test"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed leok13/udagram-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push leok13/udagram-api-feed
